[PCFG-56] added tlscert-api-config-dev-platform-pagopa-it
pagopa/gitops pull request #189
Opened 2021-11-09 17:32 UTC by aomegax

Added tlscert-api-config-dev-platform-pagopa-it

### List of changes

### Motivation and context

### Type of changes

- [X] Add new pipeline
- [ ] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [X] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-11-09 17:43 UTC, pasqualedevita requested changes

2021-11-09 17:43 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tlscert-api-config-dev-platform-pagopa-it.tf
> +  source = "git::https://github.com/pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_tls_cert?ref=v2.0.2"
```suggestion
  source = "git::https://github.com/pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_tls_cert?ref=v2.0.1"
```
please use v2.0.1 version, v2.0.2 is in preview and needs others changes (we'll schedule migration on other pr)

2021-11-09 17:43 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tlscert-api-config-dev-platform-pagopa-it.tf
> +variable "tlscert-api-config-dev-platform-pagopa-it" {
```suggestion
variable "tlscert-dev-api-config-dev-platform-pagopa-it" {
```
missing `dev-` prefix in vars and filename

2021-11-10 10:31 UTC, uolter submitted a review, later dismissed

2021-11-10 12:11 UTC, pasqualedevita requested changes

2021-11-10 12:11 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tlscert-uat-api-config-uat-platform-pagopa-it.tf
> +      dns_zone_resource_group = "pagopa-d-vnet-rg"
```suggestion
      dns_zone_resource_group = "pagopa-u-vnet-rg"
```

2021-11-10 12:11 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tlscert-uat-api-config-uat-platform-pagopa-it.tf
> +        KEY_VAULT_NAME           = "pagopa-d-kv"
```suggestion
        KEY_VAULT_NAME           = "pagopa-u-kv"
```

2021-11-10 14:39 UTC, pasqualedevita approved these changes

2021-11-10 14:41 UTC, merged

2021-11-10 14:45 UTC, pasqualedevita commented
@aomegax next times wait to merge, I need to apply change before merge