Pcfg 56 deploy api config fe
pagopa/gitops pull request #191
Opened 2021-11-11 15:00 UTC by aomegax

### List of changes

- removed tls cert for api-config
- added local vars for deploy pipeline

### Motivation and context

### Type of changes

- [ ] Add new pipeline
- [X] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [X] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-11-15 12:06 UTC, pasqualedevita approved these changes

2021-11-15 12:10 UTC, pasqualedevita requested changes

2021-11-15 12:10 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tslcert-prod-config-prod-plaform-pagopa-it.tf
> +      dns_zone_name           = "config.platform.pagopa.it"
```suggestion
      dns_record_name         = "config"
      dns_zone_name           = "platform.pagopa.it"
```
dns zone is `platform.pagopa.it` and the record `config`

2021-11-15 12:10 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tslcert-uat-config-uat-plaform-pagopa-it.tf
> +      dns_zone_name           = "config.uat.platform.pagopa.it"
```suggestion
      dns_record_name         = "config"
      dns_zone_name           = "uat.platform.pagopa.it"
```

2021-11-15 12:10 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/tslcert-dev-config-dev-plaform-pagopa-it.tf
> +      dns_zone_name           = "config.dev.platform.pagopa.it"
```suggestion
      dns_record_name         = "config"
      dns_zone_name           = "dev.platform.pagopa.it"
```

2021-11-15 12:11 UTC, pasqualedevita commented
Also a typo on file name `tslcert` instead of `tlscert`

2021-11-15 14:59 UTC, pasqualespica approved these changes
👍

2021-11-15 17:23 UTC, aomegax commented
ping @pasqualedevita

2021-11-15 17:44 UTC, pasqualedevita approved these changes

2021-11-16 11:20 UTC, pasqualedevita approved these changes

2021-11-16 11:20 UTC, merged