Selfcare interop service config
pagopa/gitops pull request #194
Opened 2021-11-18 16:16 UTC by antonioT90

### List of changes

Interop services configured

### Motivation and context

### Type of changes

- [x] Add new pipeline
- [ ] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-11-19 10:43 UTC, pasqualedevita approved these changes

2021-11-19 11:08 UTC, pasqualedevita commented
repo selfcare-uservice-party-attribute-registry-management not found

2021-11-19 11:08 UTC, pasqualedevita requested changes
repo selfcare-uservice-party-attribute-registry-management not found

2021-11-19 12:36 UTC, antonioT90 commented
fixed repo name + config changed due to SELC-181

2021-11-25 16:27 UTC, pasqualedevita approved these changes

2021-11-25 16:48 UTC, pasqualedevita approved these changes

2021-11-25 16:48 UTC, merged