[PAG-1087] enable CI and PR az pipeline triggers by yaml
pagopa/gitops pull request #205
Opened 2021-12-15 08:18 UTC by pasqualespica

Enable trigger CI and PR defined in YAML [nodo-dei-pagamenti](https://github.com/pagopa/pagopa-nodo4-nodo-dei-pagamenti) prj  

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new pipeline
- [x] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-12-15 09:28 UTC, pasqualedevita requested changes

2021-12-15 09:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti.tf
> +  ci_trigger_use_yaml           = true
```suggestion
```
`ci_trigger_use_yaml` not supported as design for code review pipelines

2021-12-15 09:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti.tf
> +  pull_request_trigger_use_yaml = true
```suggestion
```
`pull_request_trigger_use_yaml` not supported as design for deploy pipelines. If you want manual deploy from azure devops u need to remove also `ci_trigger_use_yaml`

2022-01-28 16:24 UTC, pasqualespica commented
closed for the moment. 
CI/CD for nodo-dei-pagamenti is on SIA Azure sub

2022-01-28 16:24 UTC, closed without merging