[PPR-290] Code-review pipeline for nodo-dei-pagamenti-test
pagopa/gitops pull request #227
Opened 2022-01-18 14:36 UTC by aomegax

- added code-review pipeline for pagopa-nodo-dei-pagamenti-test
- disabled deploy pipeline for pagopa-nodo-dei-pagamenti-test

depends on [PPR-291-nodo-automation @ pagopa-infra](https://github.com/pagopa/pagopa-infra/pull/111)

### List of changes

### Motivation and context

### Type of changes

- [x] Add new pipeline
- [ ] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-01-19 10:12 UTC, pasqualedevita requested changes

2022-01-19 10:12 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/pagopa-nodo-pagamenti-test.tf
> +  count  = 0
```suggestion
  count  = var.pagopa-nodo-dei-pagamenti-test.pipeline. enable_deploy == true ? 1 : 0
```
use enable/disable flag

2022-01-19 14:59 UTC, pasqualedevita approved these changes

2022-01-19 15:02 UTC, pasqualedevita requested changes
please add pagopa-bot as repo admin
```
Error: error creating resource Build Definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

  on .terraform/modules/pagopa-nodo-dei-pagamenti-test_code_review/azuredevops_build_definition_code_review/main.tf line 18, in resource "azuredevops_build_definition" "pipeline":
  18: resource "azuredevops_build_definition" "pipeline" {
```

2022-01-19 15:37 UTC, aomegax commented
> please add pagopa-bot as repo admin
> 
> ```
> Error: error creating resource Build Definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.
> 
>   on .terraform/modules/pagopa-nodo-dei-pagamenti-test_code_review/azuredevops_build_definition_code_review/main.tf line 18, in resource "azuredevops_build_definition" "pipeline":
>   18: resource "azuredevops_build_definition" "pipeline" {
> ```

done

2022-01-25 13:53 UTC, diegolagospagopa approved these changes

2022-01-25 13:55 UTC, pasqualedevita approved these changes

2022-01-25 13:55 UTC, merged