[IOPAY-148] Configure pipelines for io-pay-portal-fe and io-functions-pay-portal
pagopa/gitops pull request #30
Opened 2021-04-20 09:18 UTC by infantesimone

#### List of changes
- Add deploy and code-review pipelines for [io-pay-portal-fe](https://github.com/pagopa/io-pay-portal/tree/main/io-pay-portal-fe);
- Add deploy and code-review pipelines for [io-functions-pay-portal](https://github.com/pagopa/io-pay-portal/tree/main/io-functions-pay-portal);

2021-04-20 10:30 UTC, uolter approved these changes

2021-04-21 07:38 UTC, pasqualedevita requested changes
thanks @infantesimone for your pr, here we need to set gitgub repo name.
PS: I see that this repo has both backend and frontend, so we need some changes

also we need to change pagopa user as here https://github.com/pagopa/gitops/pull/22#issuecomment-821310752

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +      name           = "io-functions-pay-portal"
```suggestion
      name           = "io-pay-portal"
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +      pipelines_path = ".devops"
```suggestion
      pipelines_path = "."
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +    yml_path              = "${var.io-functions-pay-portal.repository.pipelines_path}/io-functions-pay-portal/code-review-pipelines.yml"
```suggestion
    yml_path              = "${var.io-functions-pay-portal.repository.pipelines_path}/io-functions-pay-portal/.devops/code-review-pipelines.yml"
```
https://github.com/pagopa/io-pay-portal/tree/main/io-functions-pay-portal/.devops
you need to rename code review file

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +  path       = "\\${var.io-functions-pay-portal.repository.name}/io-functions-pay-portal"
```suggestion
  path       = "\\${var.io-functions-pay-portal.repository.name}\io-functions-pay-portal"
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +  name       = "${var.io-functions-pay-portal.repository.name}.code-review"
```suggestion
  name       = "io-functions-pay-portal.code-review"
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +  name       = "${var.io-functions-pay-portal.repository.name}.deploy"
```suggestion
  name       = "io-functions-pay-portal.deploy"
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +  path       = "\\${var.io-functions-pay-portal.repository.name}"
```suggestion
  path       = "\\${var.io-functions-pay-portal.repository.name}\io-functions-pay-portal"
```

2021-04-21 07:38 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-functions-pay-portal.tf
> +    yml_path              = "${var.io-functions-pay-portal.repository.pipelines_path}/io-functions-pay-portal/deploy-pipelines.yml"
```suggestion
    yml_path              = "${var.io-functions-pay-portal.repository.pipelines_path}/io-functions-pay-portal/.devops/deploy-pipelines.yml"
```
https://github.com/pagopa/io-pay-portal/tree/main/io-functions-pay-portal/.devops
you need to rename deploy file

2021-04-21 11:26 UTC, pasqualedevita requested changes

2021-04-21 11:26 UTC, pasqualedevita commented on azure-devops/projects/io-pay-projects/io-pay-portal-fe.tf
> +}
```suggestion
}

resource "azurerm_role_assignment" "io-pay-deploy-azurerm-PROD-IO-iopstcdniopayportal" {
  depends_on = [data.azuread_service_principal.service_principals]

  principal_id         = data.azuread_service_principal.service_principals[local.PROD-IO-UID].id
  role_definition_name = "Storage Blob Data Contributor"
  scope                = "/subscriptions/${data.azurerm_key_vault_secret.key_vault_secret["TTDIO-PROD-IO-SUBSCRIPTION-ID"].value}/resourceGroups/${var.io-pay-portal-fe.pipeline.resource_group_azure}/providers/Microsoft.Storage/storageAccounts/${var.io-pay-portal-fe.pipeline.production_storage_account_name}"
}
```

Add permission to service principal to write into production_storage_account_name

2021-04-21 12:29 UTC, pasqualedevita submitted a review, later dismissed
LGTM

2021-04-21 13:11 UTC, pasqualedevita commented
@infantesimone can u change pipeline names here? https://github.com/pagopa/io-pay-portal/tree/main/io-functions-pay-portal/.devops

2021-04-27 16:51 UTC, GiovanniMancini commented
@pasqualedevita @uolter  We need to change a couple of environment variables in this PR. We should merge it and open another PR or do you prefer a commit on this branch?
cc: @infantesimone

2021-04-27 16:52 UTC, pasqualedevita commented
> @pasqualedevita @uolter We need to change a couple of environment variables in this PR. We should merge it and open another PR or do you prefer a commit on this branch?
> cc: @infantesimone

use this pr

2021-04-27 18:11 UTC, pasqualedevita approved these changes
Ok, project migrated into new pagopaspa devops org (https://dev.azure.com/pagopaspa/io-pay-projects)

2021-04-27 18:11 UTC, merged

2021-04-27 18:12 UTC, pasqualedevita commented
@infantesimone @GiovanniMancini tomorrow can u test that it's all ok for u? login here https://dev.azure.com/pagopaspa/io-pay-projects

2021-04-28 08:57 UTC, infantesimone commented
All pipelines are working properly, thanks @pasqualedevita