feat(io-sign): [SFEQS-1658] Add TLS cert for firma.io.italia.it
pagopa/gitops pull request #346
Opened 2023-05-10 09:53 UTC by manuelcoppotelli

### List of changes

- Defined pipeline for TLS certificate firma.io.italia.it

### Motivation and context

A TLS certificate is needed to deploy the landing page

### Type of changes

- [ ] Add new pipeline
- [ ] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2023-05-11 09:24 UTC, diegolagospagopa requested changes

2023-05-11 09:24 UTC, diegolagospagopa commented on azure-devops/projects/io-backend-projects/tlscert-prod-firma-io-italia-it.tf
> +  github_service_connection_id = azuredevops_serviceendpoint_github.io-azure-devops-github-ro.id
Please use the RW github endpoint

2023-05-11 09:44 UTC, manuelcoppotelli commented on azure-devops/projects/io-backend-projects/tlscert-prod-firma-io-italia-it.tf
> +  github_service_connection_id = azuredevops_serviceendpoint_github.io-azure-devops-github-ro.id
Fixed. Thank you

2023-05-12 12:47 UTC, diegolagospagopa approved these changes

2023-05-12 14:04 UTC, merged