Add io-functions-cgn-operator-search
pagopa/gitops pull request #41
Opened 2021-04-29 14:00 UTC by ElfoLiNk

2021-04-29 16:45 UTC, pasqualedevita requested changes
thanks @ElfoLiNk can u move this pipeline into cgn-onboarding-portal-projects?

2021-04-29 16:50 UTC, pasqualedevita requested changes

2021-04-29 16:50 UTC, pasqualedevita commented on azure-devops/projects/io-backend-projects/io-functions-cgn-operator-search.tf
> +    is_secret    = true
```suggestion
    is_secret    = true
    allow_override = false
```

2021-04-29 16:50 UTC, pasqualedevita commented on azure-devops/projects/io-backend-projects/io-functions-cgn-operator-search.tf
> +}
PROD-Esercenti

2021-04-29 16:50 UTC, pasqualedevita commented on azure-devops/projects/io-backend-projects/io-functions-cgn-operator-search.tf
> +}
remove npm connection

2021-04-30 15:51 UTC, ElfoLiNk commented
@pasqualedevita do we need other changes?

2021-04-30 16:23 UTC, pasqualedevita approved these changes
LGTM but only for code review.
For deploy I think we need some changes to manage uat and prod environments

2021-04-30 16:24 UTC, merged