[#IP-197] Add pipelines for `@pagopa/io-functions-eucovidcerts`
pagopa/gitops pull request #68
Opened 2021-05-25 10:10 UTC by gquadrati

Code review and deploy pipelines for `@pagopa/io-functions-eucovidcert`

2021-05-26 13:58 UTC, balanza requested changes
I would not use `io-backend-projects` as project, as it's for core backend services.

Create a new one, maybe `eucertcovid-projects`

2021-05-26 14:25 UTC, gquadrati commented
> I would not use `io-backend-projects` as project, as it's for core backend services.
> 
> Create a new one, maybe `eucertcovid-projects`

Done in [e6a88af](https://github.com/pagopa/gitops/pull/68/commits/e6a88af935daf7c31fb6944c3c1aec06983e0fbd)

2021-05-27 10:16 UTC, pasqualedevita commented on azure-devops/projects/eucertcovid-projects/project.tf
> +  name               = "eucertcovid-projects"
I'm going a refactor, stay tuned ;)

2021-05-27 10:20 UTC, gquadrati commented on azure-devops/projects/eucertcovid-projects/project.tf
> +  name               = "eucertcovid-projects"
Sorry, I just copied what @balanza asked in previous comment, I didn't realize the inversion

2021-05-27 10:21 UTC, pasqualedevita commented on azure-devops/projects/eucertcovid-projects/project.tf
> +  name               = "eucertcovid-projects"
wait 10 minutes to review.

2021-05-27 10:42 UTC, balanza commented on azure-devops/projects/eucertcovid-projects/project.tf
> +  name               = "eucertcovid-projects"
Sorry, my bad

2021-05-27 10:43 UTC, gquadrati commented on azure-devops/projects/eucertcovid-projects/project.tf
> +  name               = "eucertcovid-projects"
Mine too, I should have check :)

2021-05-27 10:51 UTC, pasqualedevita commented
@balanza @gquadrati please review now pipeline definition is more compact with less repeat 
https://github.com/pagopa/gitops/pull/68/commits/d855032f9e73a6b2c2dd9e21aed17bfbfb06f4f6

2021-05-27 10:55 UTC, pasqualedevita approved these changes

2021-05-27 10:59 UTC, pasqualedevita commented
@balanza @gquadrati manca il pagopa-bot sul repo

2021-05-27 11:01 UTC, pasqualedevita requested changes
permissions

2021-05-27 11:03 UTC, gquadrati commented
> permissions

Right, we need to fix all permissions in new function...

2021-05-27 11:18 UTC, pasqualedevita approved these changes

2021-05-27 12:37 UTC, balanza commented
> @balanza @gquadrati please review now pipeline definition is more compact with less repeat
> [d855032](https://github.com/pagopa/gitops/commit/d855032f9e73a6b2c2dd9e21aed17bfbfb06f4f6)

Very beautiful I like

2021-05-27 12:38 UTC, merged