Pag 287 add pagopa devops az projects
pagopa/gitops pull request #73
Opened 2021-06-11 13:52 UTC by pasqualespica

### Description

Create AZ devops project for [mockPA](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/162168930/MockPA+OnCloud+-+AZURE) ec service., to deploy [mock.ec-services-test](https://github.com/pagopa/mock.ec-services-test) nodejs express app

2021-06-11 14:28 UTC, pasqualedevita requested changes
Has pagopa-github-bot admin rights on `mock.ec-services-test`?

2021-06-11 14:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  }
do u have integrated sonar cloud?

2021-06-11 14:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  source = "git::https://github.com/pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_deploy_cstar?ref=v0.0.5"
```suggestion
  source = "git::https://github.com/pagopa/azuredevops-tf-modules.git//azuredevops_build_definition_deploy?ref=v0.0.5"
```

2021-06-11 14:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/template/template-pipeline-microservice.tf
> +variable "template-pipeline-microservice" {
remove this file

2021-06-11 14:28 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/template/template-pipeline-package.tf
> +variable "template-pipeline-package" {
remove this file

2021-06-11 14:30 UTC, pasqualedevita requested changes

2021-06-11 14:30 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  pull_request_trigger_use_yaml = true
```suggestion
```

2021-06-11 14:30 UTC, pasqualedevita commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  ci_trigger_use_yaml = true
```suggestion
```

2021-06-14 07:24 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  }
> Has pagopa-github-bot admin rights on `mock.ec-services-test`?
No, you're right, i added it to now

2021-06-14 07:25 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/mock-ec-services.tf
> +  }
> do u have integrated sonar cloud?

No, i'll remove it

2021-06-14 07:32 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/template/template-pipeline-microservice.tf
> +variable "template-pipeline-microservice" {
ok

2021-06-14 07:33 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/template/template-pipeline-package.tf
> +variable "template-pipeline-package" {
ok

2021-06-14 07:33 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/time_sleep.tf
> +# This is to work around an issue with azuredevops_resource_authorization
ok

2021-06-14 07:34 UTC, pasqualespica commented on azure-devops/projects/pagopa-projects/service_connections.tf
> +}
ok, tnx

2021-06-16 09:34 UTC, pasqualedevita approved these changes

2021-06-16 09:34 UTC, merged